name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - pathlib
  - jupyterlab
  - seaborn
  - beautifulsoup4
  - ipywidgets
  - pip
  - pip:
      # - pip 
      # - packages 
      # - go 
      # - here
